import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/facetagging">FaceTagging</Link>
        </li>
        <li>
          <Link to="/leaderboard">Leaderboard</Link>
        </li>
        <li>
          <Link to="/multiplayersupport">MultiplayerSupport</Link>
        </li>
        <li>
          <Link to="/map">Map</Link>
        </li>
        <li>
          <Link to="/scoring">Scoring</Link>
        </li>
        <li>
          <Link to="/gamescore">GameScore</Link>
        </li>
        <li>
          <Link to="/pricingengine">PricingEngine</Link>
        </li>
        <li>
          <Link to="/events">Events</Link>
        </li>
        <li>
          <Link to="/notifications">Notifications</Link>
        </li>
        <li>
          <Link to="/pushnotifications">PushNotifications</Link>
        </li>
        <li>
          <Link to="/phoneverification">PhoneVerification</Link>
        </li>
        <li>
          <Link to="/editprofile">EditProfile</Link>
        </li>
        <li>
          <Link to="/eventregistration">EventRegistration</Link>
        </li>
        <li>
          <Link to="/securitypolicy">SecurityPolicy</Link>
        </li>
        <li>
          <Link to="/signup">SignUp</Link>
        </li>
        <li>
          <Link to="/signuploginmodule">SignupLoginModule</Link>
        </li>
        <li>
          <Link to="/termsandconditions">TermsAndConditions</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
